# Generated by Django 4.1 on 2025-05-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_customer_email_alter_customer_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='flat_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street',
        ),
    ]
