# Generated by Django 4.1 on 2025-05-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_restaurant_created_at_restaurant_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='min_order',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_until',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='weekly_schedule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
