# Generated by Django 4.1 on 2025-05-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_fooditem_special_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
