# Generated by Django 4.1 on 2025-05-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
